-- Proyecto: Manejo de base de datos con SQL 
-- Autor: Rodrigo Iván González Valenzuela

USE crimen_mexico;

-- EXPLORACIÓN DE LA BASE DE DATOS 
-- Obtener la cantidad de registro
SELECT COUNT(*) AS NUM_REGISTROS
FROM raw_delitos; 
-- Obtener información de las columnas
SELECT COLUMN_NAME, DATA_TYPE, COLUMN_KEY,CHARACTER_MAXIMUM_LENGTH, 
       NUMERIC_PRECISION
FROM INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'raw_delitos'; 
-- Obtener los valores únicos en la columna
SELECT DISTINCT `Tipo de delito`
FROM raw_delitos;

-- NORMALIZACIÓN DE TABLAS
-- Renombrar las columnas 
ALTER TABLE raw_delitos
RENAME COLUMN Entidad TO ENTIDAD,
RENAME COLUMN `Cve. Municipio` TO ID_LOCACION,
RENAME COLUMN Municipio TO MUNICIPIO,
RENAME COLUMN `Bien jurídico afectado` TO BIEN_AFECTADO,
RENAME COLUMN `Tipo de delito` TO TIPO,
RENAME COLUMN `Subtipo de delito` TO SUBTIPO,
RENAME COLUMN `Modalidad` TO MODALIDAD,
RENAME COLUMN Enero TO ENERO,
RENAME COLUMN Febrero TO FEBRERO,
RENAME COLUMN Marzo TO MARZO,
RENAME COLUMN Abril TO ABRIL,
RENAME COLUMN Mayo TO MAYO,
RENAME COLUMN Junio TO JUNIO,
RENAME COLUMN Julio TO JULIO,
RENAME COLUMN Agosto TO AGOSTO,
RENAME COLUMN Septiembre TO SEPTIEMBRE,
RENAME COLUMN Octubre TO OCTUBRE,
RENAME COLUMN Noviembre TO NOVIEMBRE,
RENAME COLUMN Diciembre TO DICIEMBRE;
-- Definir ID
ALTER TABLE raw_delitos
ADD ID_DELITO INT NOT NULL UNIQUE AUTO_INCREMENT;
-- Creación de tabla con información de delitos
CREATE TABLE delitos AS
SELECT ID_DELITO, TIPO, SUBTIPO, MODALIDAD, BIEN_AFECTADO
FROM raw_delitos
ORDER BY ID_DELITO;
-- Configuración de ID_DELITO como PRIMARY KEY:
ALTER TABLE delitos
ADD PRIMARY KEY (ID_DELITO);
-- Creación de tabla con información de locaciones
CREATE TABLE locaciones AS
SELECT DISTINCT ID_LOCACION, ENTIDAD, MUNICIPIO
FROM raw_delitos
ORDER BY ENTIDAD;
-- Configuración de ID_LOCACION como PRIMARY KEY:
ALTER TABLE locaciones
ADD PRIMARY KEY (ID_LOCACION);
-- Creación de la tabla principal con todos los registros
CREATE TABLE delitos_2015 AS
SELECT ID_LOCACION, MUNICIPIO, ID_DELITO, TIPO,
	ENERO, FEBRERO, MARZO, ABRIL, MAYO, JUNIO, JULIO,
    AGOSTO, SEPTIEMBRE, OCTUBRE, NOVIEMBRE, DICIEMBRE
FROM raw_delitos;
-- Configuración de FOREIGN KEYs, ID_DELITO como PRIMARY KEY:
ALTER TABLE delitos_2015
RENAME COLUMN MUNICIPIO TO LOCACION,
ADD PRIMARY KEY (ID_DELITO),
ADD FOREIGN KEY (ID_DELITO) REFERENCES delitos(ID_DELITO),
ADD FOREIGN KEY (ID_LOCACION) REFERENCES locaciones(ID_LOCACION);

-- CREACIÓN DE FUNCIONES
-- Función para regresa el subtipo de delito dependiendo del ID
DELIMITER //
DROP FUNCTION IF EXISTS DELITO_SUBTIPO //
CREATE FUNCTION DELITO_SUBTIPO(id_del INT)
RETURNS VARCHAR(45)
READS SQL DATA
BEGIN
	DECLARE subtipo_del VARCHAR(45);
	SET subtipo_del = (SELECT SUBTIPO
	FROM delitos WHERE ID_DELITO=id_del);
    RETURN subtipo_del;
END; //
DELIMITER ; 
-- Ejemplo de uso
SELECT LOCACION, ID_DELITO, DELITO_SUBTIPO(4500) AS SUBTIPO
FROM delitos_2015
WHERE ID_DELITO=4500; 
-- Función para consultar el conteo total de un tipo de delito en una locación
DELIMITER //
DROP FUNCTION IF EXISTS DELITOS_TOTAL //
CREATE FUNCTION DELITOS_TOTAL(municipio VARCHAR(45), crimen TEXT)
RETURNS INT
READS SQL DATA
BEGIN
	DECLARE total INT;
	SELECT ENERO+FEBRERO+MARZO+ABRIL+MAYO+JUNIO+JULIO
		+AGOSTO+SEPTIEMBRE+OCTUBRE+NOVIEMBRE+DICIEMBRE
    INTO total
	FROM delitos_2015
    WHERE LOCACION=municipio AND TIPO=crimen
    GROUP BY TIPO;
    RETURN total;
END; //
DELIMITER ;
-- Ejemplo de uso
SELECT LOCACION, TIPO, DELITOS_TOTAL(LOCACION, TIPO) AS TOTAL
FROM delitos_2015
WHERE LOCACION='Hermosillo'
GROUP BY TIPO;

-- CREACIÓN DE VISTAS
-- Vista con el total de delitos para cada municipio de Sonora
CREATE VIEW SONORA_DELITOS AS
SELECT delitos_2015.ID_LOCACION, locaciones.ENTIDAD, locaciones.MUNICIPIO,
	delitos_2015.ID_DELITO, delitos.TIPO, delitos.SUBTIPO, delitos.MODALIDAD,
    ENERO+FEBRERO+MARZO+ABRIL+MAYO+JUNIO+
    JULIO+AGOSTO+SEPTIEMBRE+OCTUBRE+NOVIEMBRE+DICIEMBRE AS TOTAL 
FROM delitos_2015
LEFT JOIN locaciones ON delitos_2015.ID_LOCACION=locaciones.ID_LOCACION
LEFT JOIN delitos ON delitos_2015.ID_DELITO=delitos.ID_DELITO
WHERE ENTIDAD='Sonora';